development:
  adapter: postgresql
  encoding: unicode
  database: dragmarkers_development
  pool: 5
  username: dragmarkers
  password: dragmarkers

test:
  adapter: postgresql
  encoding: unicode
  database: dragmarkers_test
  pool: 5
  username: dragmarkers
  password: dragmarkers

